DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS light;
DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS moisture;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  street TEXT NOT NULL,
  city TEXT NOT NULL,
  zip TEXT NOT NULL,
  password TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE light (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lumens DECIMAL NOT NULL,
  datetime TIMESTAMP NOT NULL
);

CREATE TABLE temperature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  degrees DECIMAL NOT NULL,
  datetime TIMESTAMP NOT NULL
);

CREATE TABLE moisture (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  humidity DECIMAL NOT NULL,
  datetime TIMESTAMP NOT NULL
);